# Generated by Django 2.0.2 on 2018-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('trigger', models.CharField(max_length=200)),
                ('response', models.TextField()),
                ('source_state', models.CharField(max_length=200)),
                ('dest_state', models.CharField(max_length=200)),
                ('is_globstar', models.NullBooleanField(choices=[(None, ''), (True, 'Yes'), (False, 'No')], default=None, max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
