
# TODO: only list exceptions that are not easy to generate using simple "add s" rules.
PLURALS = {
    'apple': 'apples',
    'backpack': 'backpacks',
    'ball': 'balls',
    'banana': 'bananas',
    'baseball bat': 'baseball bats',
    'baseball glove': 'baseball gloves',
    'bear': 'bears',
    'bed': 'beds',
    'bench': 'benches',
    'bicycle': 'bicycles',
    'bird': 'birds',
    'boat': 'boats',
    'book': 'books',
    'bottle': 'bottles',
    'bowl': 'bowls',
    'broccoli': 'broccoli bunches',
    'bus': 'busses',
    'cake': 'cakes',
    'car': 'cars',
    'carrot': 'carrots',
    'cat': 'cats',
    'chair': 'chairs',
    'clock': 'clocks',
    'couch': 'couches',
    'cow': 'cows',
    'cup': 'cups',
    'dining table': 'dining tables',
    'dog': 'dogs',
    'donut': 'donuts',
    'elephant': 'elephants',
    'fire hydrant': 'fire hydrants',
    'fork': 'forks',
    'frisbee': 'frisbees',
    'giraffe': 'giraffes',
    'hair drier': 'hair driers',
    'handbag': 'handbags',
    'horse': 'horses',
    'hot dog': 'hot dogs',
    'keyboard': 'keyboards',
    'kite': 'kites',
    'knife': 'knives',
    'laptop': 'laptops',
    'microwave': 'microwave ovens',
    'mobile phone': 'mobile phones',
    'monitor': 'monitors',
    'motorcycle': 'motorcycles',
    'mouse': 'mice',
    'orange': 'oranges',
    'oven': 'ovens',
    'parking meter': 'parking meters',
    'person': 'people',
    'pizza': 'pizzas',
    'plane': 'planes',
    'potted plant': 'potted plants',
    'refrigerator': 'refrigerators',
    'remote': 'remotes',
    'sandwich': 'sandwiches',
    'scissors': 'pairs of scissors',
    'sheep': 'sheep',
    'sink': 'sinks',
    'skateboard': 'skateboards',
    'skis': 'pairs of skis',
    'snowboard': 'snowboards',
    'spoon': 'spoons',
    'stop sign': 'stop signs',
    'suitcase': 'suitcases',
    'surfboard': 'surfboards',
    'teddy bear': 'teddy bears',
    'tennis racket': 'tennis rackets',
    'tie': 'ties',
    'toaster': 'toasters',
    'toilet': 'toilets',
    'toothbrush': 'toothbrushes',
    'traffic light': 'traffic lights',
    'train': 'trains',
    'truck': 'trucks',
    'umbrella': 'umbrellas',
    'vase': 'vases',
    'wine glass': 'wine glasses',
    'zebra': 'zebras'}


SINGULAR = dict(list(zip(PLURALS.values(), PLURALS.keys())))
