name: aichat
channels: !!python/tuple
  - menpo
  - conda-forge
  - defaults
  - akode
dependencies:
  - python==3.6
#  - opencv
  - cffi
  - jasper
#  - matplotlib
  - numpy
  - pandas
  - pillow
#  - pyqt
  - pytest
  - pytest-cov
  - portaudio
  - readline     
  - scipy
  - swig
  - speechrecognition
  - gensim
  - boto3
  - regex==2017.4.5
  - scipy==0.19.1
  - scikit-learn==0.19.1
  - scikit-image==0.13.1
  - pip:
    - exrex
#    - google-cloud-vision
    - paho-mqtt
#    - pocketsphinx
#    - pyaudio
    - pyttsx3
    - soundfile
    - tensorflow==1.2.0
    - vocabulary
