# Generated by Django 2.0.5 on 2018-05-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chatapp.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chatapp.node'),
        ),
    ]
