# Generated by Django 2.0.5 on 2018-05-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_auto_20180525_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='chatapp.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='response',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='chatapp.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='trigger',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
