---

- name: Provision a {{ application_name }} web server
  hosts: "{{ application_name }}"
  become: yes
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base