---

- name: Initial configuration for a {{ application_name }} server
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - roles/base/defaults/main.yml

  roles:
    - security
