---

- name: Use molecule to test all roles in the playbook.
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    update_apt_cache: yes
    force_ssh_authentication: no
    ansible_python_interpreter: /usr/bin/python
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - security
    - base
    - db
    - rabbitmq
    - web
    - celery
    - nginx
