---
- hosts: all
  gather_facts: no
  tasks:
    - name: Running update and safe-upgrade
      apt:
        update_cache=yes
        upgrade=safe
      register: result
    - debug: var=result.stdout_lines
