---
- hosts: all
  become: yes
  become_user: ubuntu
  gather_facts: no

  tasks:
  - name: pull branch {{ version }}
    git:
      repo={{ repo_url }}/{{ repo_name }}.git
      dest={{ repo_dir }}
      version={{ version }}
      accept_hostkey=yes

- hosts: all
  gather_facts: no
  tasks:
  - name: install python requirements
    pip: requirements={{ repo_dir }}/requirements/production.txt extra_args=--upgrade

- hosts: all
  become: yes
  become_user: ubuntu
  gather_facts: no
  environment:
    DJANSIBLE_HOSTNAME: "{{ hostname }}"
    DJANSIBLE_DBHOST: "{{ dbhost }}"
    DJANSIBLE_DBUSER: "{{ dbuser }}"
    DJANSIBLE_DBNAME: "{{ dbname }}"
    DJANSIBLE_DBPASSWORD: "{{ dbpassword }}"
    DJANGO_SETTINGS_MODULE: "{{ django_project }}.settings.production"
    DATABASE_URL: postgres://{{ dbuser }}:{{ dbpassword }}@{{ dbhost }}/{{ dbname }}
    STATIC_ROOT: "{{ static_dir }}"

  tasks:
  - name: create static_root dir
    file: path={{ static_dir }} state=directory mode=0755
  - name: create static_files dir
    file: path={{ django_dir }}/{{ django_project }}/static state=directory mode=0755
  - name: django collectstatic
    shell: ./manage.py collectstatic --noinput chdir={{ django_dir }}
  - name: django migrate
    shell: ./manage.py migrate --noinput chdir={{ django_dir }}
  - name: django auth.User fixture in users.json
    template: src=../config/users.json dest={{ django_dir }}/users.json
  - name: django loaddata
    shell: ./manage.py loaddata users chdir={{ django_dir }}

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: uwsgi config file
    template: src=../config/uwsgi.ini dest=/etc/uwsgi/apps-enabled/{{ django_project }}.ini
    register: uwsgi_config
  - name: uwsgi restart
    service: name=uwsgi state=restarted
    when: uwsgi_config.changed
  # - name: uwsgi restart
  #   service: name=uwsgi state=restarted
